# Generated by Django 5.1.4 on 2024-12-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="color",
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.TextField(max_length=4, null=True),
        ),
    ]
